name: ⚙️ Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checkout repository branch
        uses: actions/checkout@v7

      - name: 📥 Install pnpm
        uses: pnpm/action-setup@v6

      - name: 🟢 Use Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - name: ⬇️ Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: 🧪 Run tests
        run: pnpm test
